/**
 * Static project structure: paths, DAG topology, language and package
 * definitions, and the target output formats supported by language CLIs.
 */

import path from "path";
import { LanguageConfig, NodeInfo } from "./types";

// ============================================================
// Paths
// ============================================================

export const ROOT = path.resolve(__dirname, '../..')
export const LOGS_DIR = path.join(ROOT, "examples", "programs", "logs");
export const PROGRAMS_FOLDER = path.join(ROOT, "examples", "programs");

// ============================================================
// Languages & packages
// ============================================================

/**
 * Specifications of each language supported by the project.
 * Each entry describes how to install and configure the compiler
 * generated by TCOS for that language.
 * 
 * To add a new language, add an entry here AND a matching node
 * in {@link DAG} under `examples/languages`.
 */
export const LANGUAGES: Record<string, LanguageConfig> = {
    "ParLang": {
        extension: ".parlang",
        npmLinks: ["ccfg", "backend-compiler"],
        tcosFile: "parlang.tcos"
    },
    "simpleL": {
        extension: ".simple",
        npmLinks: ["ccfg", "backend-compiler"],
        tcosFile: "simpleL.tcos"
    },
    "fsm": {
        extension: ".fsm",
        npmLinks: ["ccfg", "backend-compiler"],
        tcosFile: "testFSM.sos"
    }
};

/**
 * Local npm packages and the local packages they depend on.
 *
 * Used by the installer to drive `npm link <deps>` in the right
 * order. Keep in sync with {@link DAG} when adding a package.
 */
export const PACKAGES: Record<string, string[]> = {
    "ccfg": [],
    "backend-compiler": ["ccfg"],
    "interpreter": ["ccfg", "backend-compiler"],
    "tcos": []
};

/**
 * Output formats the language CLIs can target.
 * Order matters: it drives the order in interactive prompts and
 * batch reports.
 */
export const TARGET_FORMATS = ["C++", "Python", "JavaScript"];

// ============================================================
// Project structure (DAG)
// ============================================================

/**
 * Project structure as a directed acyclic graph.
 *
 * Each entry tells (1) where the node lives on disk (`packages/` or `examples/languages/`) and 
 * (2) which other nodes must be built before it. 
 * The watcher walks this graph to compute rebuild cascades — see {@link computeCascade}.
 */
export const DAG: Record<string, NodeInfo> = {
    "ccfg": {
        folder: "packages",
        dependsOn: []
    },
    "backend-compiler": {
        folder: "packages",
        dependsOn: ["ccfg"]
    },
    "interpreter": {
        folder: "packages",
        dependsOn: ["ccfg", "backend-compiler"]
    },
    "tcos": {
        folder: "packages",
        dependsOn: []
    },
    "ParLang": {
        folder: "examples/languages",
        dependsOn: ["ccfg", "backend-compiler", "tcos"]
    },
    "simpleL": {
        folder: "examples/languages",
        dependsOn: ["ccfg", "backend-compiler", "tcos"]
    },
    "fsm": {
        folder: "examples/languages",
        dependsOn: ["ccfg", "backend-compiler", "tcos"]
    }
};