import { Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule,DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, PartialLangiumServices } from 'langium/lsp';
import { ParLangGeneratedModule, ParLangGeneratedSharedModule } from './generated/module.js';
import { ParLangValidator, registerValidationChecks } from './par-lang-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ParLangAddedServices = {
    validation: {
        ParLangValidator: ParLangValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ParLangServices = LangiumServices & ParLangAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ParLangModule: Module<ParLangServices, PartialLangiumServices & ParLangAddedServices> = {
    validation: {
        ParLangValidator: () => new ParLangValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createParLangServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    ParLang: ParLangServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ParLangGeneratedSharedModule
    );
    const ParLang = inject(
        createDefaultModule({ shared }),
        ParLangGeneratedModule,
        ParLangModule
    );
    shared.ServiceRegistry.register(ParLang);
    registerValidationChecks(ParLang);
    return { shared, ParLang };
}
