import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { FiniteStateMachineGeneratedModule, FiniteStateMachineGeneratedSharedModule } from './generated/module';
import { FiniteStateMachineValidator, registerValidationChecks } from './finite-state-machine-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type FiniteStateMachineAddedServices = {
    validation: {
        FiniteStateMachineValidator: FiniteStateMachineValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type FiniteStateMachineServices = LangiumServices & FiniteStateMachineAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const FiniteStateMachineModule: Module<FiniteStateMachineServices, PartialLangiumServices & FiniteStateMachineAddedServices> = {
    validation: {
        FiniteStateMachineValidator: () => new FiniteStateMachineValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createFiniteStateMachineServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    FiniteStateMachine: FiniteStateMachineServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        FiniteStateMachineGeneratedSharedModule
    );
    const FiniteStateMachine = inject(
        createDefaultModule({ shared }),
        FiniteStateMachineGeneratedModule,
        FiniteStateMachineModule
    );
    shared.ServiceRegistry.register(FiniteStateMachine);
    registerValidationChecks(FiniteStateMachine);
    return { shared, FiniteStateMachine };
}
