import { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { SimpleLValidator } from './simple-l-validator';
/**
 * Declaration of custom services - add your own service classes here.
 */
export type SimpleLAddedServices = {
    validation: {
        SimpleLValidator: SimpleLValidator;
    };
};
/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SimpleLServices = LangiumServices & SimpleLAddedServices;
/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export declare const SimpleLModule: Module<SimpleLServices, PartialLangiumServices & SimpleLAddedServices>;
/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export declare function createSimpleLServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices;
    SimpleL: SimpleLServices;
};
